# Generated by Django 4.0 on 2022-05-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todomodel',
            options={'ordering': ['-timestamps']},
        ),
    ]
